services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://server:8080
